import json
from logging import Logger
from types import TracebackType
from .consts import Feature, OSCompatibility
from .types import Achievement, Authentication, Game, GameLibrarySettings, GameTime, LocalGame, NextStep, Subscription, SubscriptionGame, UserInfo, UserPresence
from typing import Any, AsyncGenerator, Coroutine, Dict, Generic, List, Optional, Type, TypeVar, Union

logger: Logger

class JSONEncoder(json.JSONEncoder):
    def default(self, o: Any): ...

#_AchievementContext = TypeVar('_AchievementContext')
#_GameTimeContext = TypeVar('_GameTimeContext')
#_LibrarySettingContext = TypeVar('_LibrarySettingContext')
#_OSCompatibilityContext = TypeVar('_OSCompatibilityContext')
#_UserPresenceContext = TypeVar('_UserPresenceContext')
#_LocalSizeContext = TypeVar('_LocalSizeContext')
#_SubscriptionGameContext = TypeVar('_SubscriptionGameContext')
#class Plugin(Generic[_AchievementContext, _GameTimeContext, _LibrarySettingContext, _OSCompatibilityContext , _UserPresenceContext, _LocalSizeContext, _SubscriptionGameContext]):
class Plugin():
    def __init__(self, platform, version, reader, writer, handshake_token) -> None: ...
    async def __aenter__(self): ...
    async def __aexit__(self, exc_type: Optional[Type], exc: Optional[BaseException], tb: Optional[TracebackType]) -> None: ...
    @property
    def features(self) -> List[Feature]: ...
    @property
    def persistent_cache(self) -> Dict[str, str]: ...
    async def run(self) -> None: ...
    def close(self) -> None: ...
    async def wait_closed(self) -> None: ...
    def create_task(self, coro: Coroutine[None, None, Any], description: str): ...
    def store_credentials(self, credentials: Dict[str, Any]) -> None: ...
    def add_game(self, game: Game) -> None: ...
    def remove_game(self, game_id: str) -> None: ...
    def update_game(self, game: Game) -> None: ...
    def unlock_achievement(self, game_id: str, achievement: Achievement) -> None: ...
    def update_local_game_status(self, local_game: LocalGame) -> None: ...
    def add_friend(self, user: UserInfo) -> None: ...
    def remove_friend(self, user_id: str) -> None: ...
    def update_friend_info(self, user: UserInfo) -> None: ...
    def update_game_time(self, game_time: GameTime) -> None: ...
    def update_user_presence(self, user_id: str, user_presence: UserPresence) -> None: ...
    def lost_authentication(self) -> None: ...
    def push_cache(self) -> None: ...
    async def refresh_credentials(self, params: Dict[str, Any], sensitive_params: Union[bool, List[str]]) -> Dict[str, Any]: ...
    def handshake_complete(self) -> None: ...
    def tick(self) -> None: ...
    async def shutdown(self) -> None: ...
    async def authenticate(self, stored_credentials: Optional[Dict[str, Any]]) -> Union[NextStep, Authentication]: ...
    async def pass_login_credentials(self, step: str, credentials: Dict[str, str], cookies: List[Dict[str, str]]) -> Union[NextStep, Authentication]: ...
    async def get_owned_games(self) -> List[Game]: ...
    #async def prepare_achievements_context(self, game_ids: List[str]) -> _AchievementContext: ...
    #async def get_unlocked_achievements(self, game_id: str, context: _AchievementContext) -> List[Achievement]: ...
    async def prepare_achievements_context(self, game_ids: List[str]) -> Any: ...
    async def get_unlocked_achievements(self, game_id: str, context: Any) -> List[Achievement]: ...
    def achievements_import_complete(self) -> None: ...
    async def get_local_games(self) -> List[LocalGame]: ...
    async def launch_game(self, game_id: str) -> None: ...
    async def install_game(self, game_id: str) -> None: ...
    async def uninstall_game(self, game_id: str) -> None: ...
    async def shutdown_platform_client(self) -> None: ...
    async def launch_platform_client(self) -> None: ...
    async def get_friends(self) -> List[UserInfo]: ...
    #async def prepare_game_times_context(self, game_ids: List[str]) -> _GameTimeContext: ...
    #async def get_game_time(self, game_id: str, context: _GameTimeContext) -> GameTime: ...
    async def prepare_game_times_context(self, game_ids: List[str]) -> Any: ...
    async def get_game_time(self, game_id: str, context: Any) -> GameTime: ...
    def game_times_import_complete(self) -> None: ...
    #async def prepare_game_library_settings_context(self, game_ids: List[str]) -> _LibrarySettingContext: ...
    #async def get_game_library_settings(self, game_id: str, context: _LibrarySettingContext) -> GameLibrarySettings: ...
    async def prepare_game_library_settings_context(self, game_ids: List[str]) -> Any: ...
    async def get_game_library_settings(self, game_id: str, context: Any) -> GameLibrarySettings: ...
    def game_library_settings_import_complete(self) -> None: ...
    #async def prepare_os_compatibility_context(self, game_ids: List[str]) -> _OSCompatibilityContext: ...
    #async def get_os_compatibility(self, game_id: str, context: _OSCompatibilityContext) -> Optional[OSCompatibility]: ...
    async def prepare_os_compatibility_context(self, game_ids: List[str]) -> Any: ...
    async def get_os_compatibility(self, game_id: str, context: Any) -> Optional[OSCompatibility]: ...
    def os_compatibility_import_complete(self) -> None: ...
    #async def prepare_user_presence_context(self, user_id_list: List[str]) -> _UserPresenceContext: ...
    #async def get_user_presence(self, user_id: str, context: _UserPresenceContext) -> UserPresence: ...
    async def prepare_user_presence_context(self, user_id_list: List[str]) -> Any: ...
    async def get_user_presence(self, user_id: str, context: Any) -> UserPresence: ...
    def user_presence_import_complete(self) -> None: ...
    #async def prepare_local_size_context(self, game_ids: List[str]) -> _LocalSizeContext: ...
    #async def get_local_size(self, game_id: str, context: _LocalSizeContext) -> Optional[int]: ...
    async def prepare_local_size_context(self, game_ids: List[str]) -> Any: ...
    async def get_local_size(self, game_id: str, context: Any) -> Optional[int]: ...
    def local_size_import_complete(self) -> None: ...
    async def get_subscriptions(self) -> List[Subscription]: ...
    #async def prepare_subscription_games_context(self, subscription_names: List[str]) -> _SubscriptionGameContext: ...
    #async def get_subscription_games(self, subscription_name: str, context: _SubscriptionGameContext) -> AsyncGenerator[List[SubscriptionGame], None]: ...
    async def prepare_subscription_games_context(self, subscription_names: List[str]) -> Any: ...
    async def get_subscription_games(self, subscription_name: str, context: Any) -> AsyncGenerator[List[SubscriptionGame], None]: ...
    def subscription_games_import_complete(self) -> None: ...

def create_and_run_plugin(plugin_class: Type, argv: List[str]) -> None: ...
