from typing import Iterable, Optional

class ProcessInfo:
    pid: int
    binary_path: Optional[str]
    def __init__(self, pid: int, binary_path: Optional[str]) -> None: ...

def pids() -> Iterable[int]: ...
def get_process_info(pid: int) -> Optional[ProcessInfo]: ...
def process_iter() -> Iterable[Optional[ProcessInfo]]: ...
