from logging import Logger
from typing import Any, Coroutine

logger: Logger

class TaskManager:
    def __init__(self, name: str) -> None: ...
    def create_task(self, coro : Coroutine[None, None, Any], description: str, handle_exceptions: bool = ...): ...
    def cancel(self) -> None: ...
    async def wait(self) -> None: ...
